List targets when focus specified without argument
Previously specifying a focus with an invalid argument showed a list of
possibilities, but leaving off the argument just showed a static error:

    ❯ cargo asm --bench
    --bench requires an argument
    ❯ cargo asm --bench foo
    error: no bench target named `foo`.
    Available bench targets:
        escape
        unescape
        helpers

    Cargo failed with exit status: 101

This changes the focus options to display the list of possible targets
when the argument is left off:

    ❯ cargo asm --bench
    error: "--bench" takes one argument.
    Available benches:
        escape
        helpers
        unescape

    Cargo failed with exit status: 101

This does not change the --help message since leaving off the argument
is still an error and results in an exit code.